import { Link } from 'react-router-dom';
import Header from '../components/Header'; import Footer from '../components/Footer'; import Marquee from '../components/Marquee'; import Picture from '../components/Picture'; import Seo from '../components/Seo';
import { projects } from '../data/projects'; import { experience } from '../data/experience';

const reviews = [
  ['Loved working with her. I wasn’t sure what direction to go, and she really knocked it out of the park. Super professional, and the process came out great.','oddandbuckley · United States'],
  ['I have worked with many creative people on Fiverr, but Lyba is unique. She implemented my idea really well. She is an asset to every project.','francooooo11111 · Germany'],
  ['Perfectly executed the job on the first try. Accommodated a last-minute request. The typography, font and colour grading were executed at a very high level.','bern06 · United States']
];

export default function HomePage(){return <>
<Seo title="Laiba Ayyaz — Graphic Designer & Print Production Specialist" description="Portfolio of Laiba Ayyaz, a Vancouver-based graphic designer specializing in print production, branding, packaging and visual communication." />
<Header />
<main>
<section className="hero"><div className="hero-shell"><div className="hero-copy"><div className="eyebrow">HELLO, I'M</div><h1 className="hero-name">Laiba<br/>Ayyaz</h1><div className="hero-tagline">Graphic designer + print production specialist</div><p className="hero-sub">I design branding, packaging and marketing materials with the production knowledge to carry the work from first concept to polished, press-ready files.</p><div className="stat-row"><div className="stat"><div className="num coral">7+</div><div className="lbl">Years experience</div></div><div className="stat"><div className="num teal">1,500+</div><div className="lbl">Projects delivered</div></div><div className="stat"><div className="num yellow">5.0</div><div className="lbl">Client rating</div></div></div><div className="hero-actions"><a className="btn primary" href="#work">Explore my work →</a><span className="scroll-hint">↓ Scroll to discover</span></div></div><div className="hero-media"><Picture src="profile/laiba-hero-clean.webp" alt="Portrait of Laiba Ayyaz" loading="eager" fetchPriority="high" /></div></div><Marquee /></section>
<section id="work"><div className="wrap"><div className="sec-head"><h2>Selected work.</h2><p>Four projects across packaging, brand identity, marketing and prepress, focused on work designed to communicate clearly and reproduce beautifully.</p></div><div className="project-list">{projects.map(p=><Link className="project-row" key={p.slug} to={`/work/${p.slug}`}><span className="project-num">{p.number}</span><div className="project-thumb"><Picture src={p.hero} alt="" /></div><div><h3>{p.title}</h3><p>{p.summary}</p><div className="tags">{p.tags.slice(0,2).map(t=><span key={t}>{t}</span>)}</div></div><span className="arrow">→</span></Link>)}</div></div></section>
<section id="expertise" className="soft-section"><div className="wrap"><div className="sec-head"><h2>Design that holds up in production.</h2><p>My work sits where visual design and real-world production meet, from identity systems to press-ready execution.</p></div><div className="expertise-grid"><article><span>01</span><h3>Branding & print</h3><p>Identity, packaging, editorial and marketing work built for both screen and physical production.</p></article><article><span>02</span><h3>Print production</h3><p>Bleed, trim, colour, separations, finishing and file setup handled with production in mind from the start.</p></article><article><span>03</span><h3>Marketing & editorial</h3><p>Campaigns, presentations and promotional pieces shaped around hierarchy, audience and brand consistency.</p></article></div></div></section>
<section id="experience"><div className="wrap"><div className="sec-head"><div><div className="kicker">2019 — Present · 7+ years in practice</div><h2>Experience & education.</h2></div><p>From freelance to in-house prepress to design coordination, each role added a different layer of production discipline.</p></div>{experience.map(e=><article className="exp-row" key={e.date+e.role}><div className="exp-date">{e.date}</div><div><h3>{e.role}</h3><div className="company">{e.company}</div><p>{e.description}</p><div className="tags">{e.tags.map(t=><span key={t}>{t}</span>)}</div></div></article>)}</div></section>
<section id="reviews" className="soft-section"><div className="wrap"><div className="sec-head"><h2>What clients say.</h2><p>Selected five-star feedback across branding, print, packaging and visual communication.</p></div><div className="reviews">{reviews.map(([q,w])=><blockquote key={w}><div className="stars">★★★★★ <strong>5.0</strong></div><p>“{q}”</p><cite>{w}</cite></blockquote>)}</div></div></section>
</main><Footer /></>;}